Repository gardener/kube-rbac-proxy-watcher, pull requests merged in 2025-04, with the labels that each got.

#41 Update go module dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#42 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, reviewed/lgtm, size/xs

#44 Simple linter configuration
  .golangci.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#45 Update tool dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#46 Update dependabot configuration
  .github/dependabot.yml
Labels: needs/ok-to-test, needs/review, size/xs

#50 Update tool dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m
